# Generated by Django 3.2.7 on 2021-10-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rent', models.IntegerField(max_length=30)),
                ('location', models.CharField(max_length=500)),
                ('residents', models.IntegerField(max_length=30)),
            ],
        ),
    ]
