# Generated by Django 3.2.7 on 2021-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='bath',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='imgadd',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='housing',
            name='residents',
            field=models.IntegerField(),
        ),
    ]
