# Generated by Django 3.2.5 on 2021-11-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_auto_20211031_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='description',
            field=models.CharField(default='This is a housing', max_length=1000),
        ),
    ]
