# Generated by Django 3.2.7 on 2021-11-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0004_auto_20211108_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='bath',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='housing',
            name='bed',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='housing',
            name='rent',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='housing',
            name='residents',
            field=models.IntegerField(max_length=500),
        ),
    ]
