# Generated by Django 3.2.7 on 2021-11-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_auto_20211112_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='residents',
        ),
        migrations.AddField(
            model_name='housing',
            name='footage',
            field=models.CharField(default='500 ft', max_length=500),
        ),
        migrations.AddField(
            model_name='housing',
            name='link',
            field=models.CharField(default='description of housing option', max_length=1000),
        ),
    ]
