# Generated by Django 3.2.7 on 2021-11-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0006_auto_20211112_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='footage',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='housing',
            name='imgadd',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='rent',
            field=models.IntegerField(),
        ),
    ]
