# Generated by Django 3.2.7 on 2021-11-15 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth_app', '0007_auto_20211112_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
