# Generated by Django 3.2.7 on 2021-11-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0007_auto_20211112_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='description',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='imgadd',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='link',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
