# Generated by Django 3.2.7 on 2021-11-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0008_auto_20211115_1445'),
        ('oauth_app', '0008_housing_favorites'),
    ]

    operations = [
    ]
