# Generated by Django 3.2.5 on 2021-11-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0009_merge_0008_auto_20211115_1445_0008_housing_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
