# Generated by Django 3.2.5 on 2021-11-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0010_housing_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='num_surveys',
            field=models.IntegerField(default=0),
        ),
    ]
