# Generated by Django 3.2.5 on 2021-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0011_auto_20211129_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
